# Generated by Django 4.2.30 on 2026-05-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.TextField(blank=True),
        ),
    ]
