# Generated by Django 4.2.30 on 2026-05-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='excerpt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='excerpt',
        ),
    ]
